name: Build and push Sakura image
on: [push]
jobs:
  build-push-sakura:
    container:
      image: ghcr.io/lolibrary/build/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sakura
        uses: actions/checkout@v2
        with:
          path: sakura
      - name: Checkout build tools
        uses: actions/checkout@v2
        with:
          repository: lolibrary/build
          token: ${{ secrets.PAT }}
      - name: GHCR login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: docker.pkg.github.com
      - name: Build image
        shell: zsh
        run: |
          composer config http-basic.nova.laravel.com $NOVA_USERNAME $NOVA_API_KEY
          ./build.zsh
    env:
      NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
      NOVA_API_KEY: ${{ secrets.NOVA_API_KEY }}
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}