name: Build and push Sakura image
on: [push]
jobs:
  build-push-sakura:
    container:
      image: ghcr.io/lolibrary/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build tools
        uses: actions/checkout@v2
        with:
          repository: lolibrary/build
          token: ${{ secrets.PAT }}
      - name: Checkout Sakura
        uses: actions/checkout@v2
        with:
          path: cache
      - name: GHCR login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
      - name: Install Dependencies
        shell: zsh -eo pipefail {0}
        run: |
          ls
          print $COMPOSER_AUTH
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_API_KEY }} --no-interaction --working-dir cache
          print -P "🐙 %F{green}$GITHUB_SHA%f"
          print "📲 Installing dependencies"
          print -P -n "    %F{red}composer%f    "
          composer install --no-interaction --working-dir cache
          print "✅"
          print -P -n "    %F{red}node.js%f     "
          npm install --prefix cache
          print "✅"
      - name: Build App
        shell: zsh -eo pipefail {0}
        run: npm run production --prefix $cache
      - name: Docker Build & Push
        shell: zsh -eo pipefail {0}
        run: |
          docker build -t $DOCKER_SHA_TAG .
          docker push $DOCKER_SHA_TAG
    env:
      DOCKER_SHA_TAG: "ghcr.io/lolibrary/sakura:$GITHUB_SHA"
      NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
      NOVA_API_KEY: ${{ secrets.NOVA_API_KEY }}
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      PIPELINE: "true"
      COMPOSER_AUTH: '{"http-basic": {"http-basic.nova.laravel.com": {"username": "${{ secrets.NOVA_USERNAME }}", "password": "${{ secrets.NOVA_API_KEY }}"}}}'
