name: Deploy Sakura
on: [workflow_dispatch]
jobs:
  deploy-sakura:
    container:
      image: ghcr.io/lolibrary/builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build tools
        uses: actions/checkout@v2
        with:
          repository: lolibrary/build
          token: ${{ secrets.PAT }}
      - name: GHCR login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
      - name: Deploy
        run: |
          cat "$(pwd)/manifests/prod.yml" | sed "s#PLACEHOLDER#\"$DOCKER_SHA_TAG\"#"
          kubectl rollout status "deployment/s-sakura"

    env:
      DOCKER_SHA_TAG: "ghcr.io/lolibrary/sakura:${{ github.sha }}"
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      NAMESPACE: "default"

