name: Deploy Sakura to Stage
on: [workflow_dispatch]
jobs:
  deploy-sakura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build tools
        uses: actions/checkout@v2
        with:
          repository: lolibrary/build
          token: ${{ secrets.PAT }}
      - name: GCloud login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: GHCR login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
      - name: Configure kubectl creds
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy
        run: |
          docker pull $DOCKER_WIKI_REPO:latest
          export WIKI_TAG=$(docker image inspect -f "{{(index .RepoDigests 0)}}" $DOCKER_WIKI_REPO:latest)
          cat "$(pwd)/manifests/stage.yml" | sed "s#PLACEHOLDER#\"$DOCKER_SHA_TAG\"#" |  sed "s#WIKIHOLDER#\"$WIKI_TAG\"#" | kubectl apply --record -f -
          kubectl rollout status "deployment/s-sakura" -n $NAMESPACE

    env:
      DOCKER_SHA_TAG: "ghcr.io/lolibrary/sakura:${{ github.sha }}"
      DOCKER_WIKI_REPO: "ghcr.io/lolibrary/wiki"
      PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
      NAMESPACE: "default"
      GKE_CLUSTER: "staging"
      GKE_ZONE: "us-central1-a"
