name: Start Staging Cluster
on: [workflow_dispatch]
jobs:
  deploy-sakura:
    runs-on: ubuntu-latest
    steps:
      - name: GCloud login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: Start 
        run: gcloud container clusters create "$GKE_CLUSTER" --zone "$GKE_ZONE"
    env:
      GKE_CLUSTER: "staging"
      GKE_ZONE: "us-central1-a"
