name: Start Staging Cluster
on: [workflow_dispatch]
jobs:
  start-stage:
    runs-on: ubuntu-latest
    steps:
      - name: GCloud login
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: Log into prod cluster
        run: gcloud container clusters get-credentials "$PROD_CLUSTER" --zone "$GKE_ZONE"
      - name: Copy secrets
        run: |
            kubectl get secret cloudsql-instance-credentials -oyaml > instance.creds
            kubectl get secret cloudsql-db-credentials -oyaml > db.creds
            kubectl get secret digitalocean-spaces -oyaml > do.creds
      - name: Create cluster 
        run: gcloud container clusters create "$STAGE_CLUSTER" --zone "$GKE_ZONE"
      - name: Add secrets
        run: |
          kubectl create secret docker-registry ghcr --docker-server="https://ghcr.io" --docker-username=${{ github.actor }} --docker-password=${{ secrets.PAT }}
          kubectl create -f ./instance.creds
          kubectl create -f ./db.creds
          kubectl create -f ./do.creds
          rm *.creds
    env:
      STAGE_CLUSTER: "staging"
      PROD_CLUSTER: "lolibrary"
      GKE_ZONE: "us-central1-a"
