name: Stop Staging Cluster
on: [workflow_dispatch]
jobs:
  deploy-sakura:
    runs-on: ubuntu-latest
    steps:
      - name: GCloud login
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
      - name: Stop stage 
        run: gcloud container clusters delete "$GKE_CLUSTER" --zone "$GKE_ZONE" --quiet
    env:
      GKE_CLUSTER: "staging"
      GKE_ZONE: "us-central1-a"
